# -*- coding: utf-8 -*-
"""INTERN_P2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14gNOTzfp5InP9BG7WvyizRpQF2JTKS3k
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_excel('/content/Dataset for Data Analytics (1).xlsx')

df

print('fist 10 rows')
df.head(10)

print(df.info())

print(df.shape)

print("MISSING VALUES")
print(df.isnull().sum())

print("STATISTICAL SUMMARY")
print(df.describe())

print("MEAN VALUES")
print(df.mean(numeric_only=True))

df.median(numeric_only=True)

df.count()

df.duplicated().sum()

df = df.drop_duplicates()

df.corr(numeric_only=True)

df.hist(figsize=(12,10))
plt.show()

numeric_cols = df.select_dtypes(include=np.number).columns

for col in numeric_cols:
    plt.figure(figsize=(6,4))
    plt.boxplot(df[col].dropna())
    plt.title(f'Boxplot of {col}')
    plt.show()

for col in numeric_cols:
    plt.figure(figsize=(8,4))
    plt.plot(df[col])
    plt.title(f'Trend of {col}')
    plt.xlabel('Index')
    plt.ylabel(col)
    plt.show()

cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print(f"\nVALUE COUNTS FOR {col}")
    print(df[col].value_counts())

df.to_excel('/content/EDA_Result.xlsx', index=False)

print("\nEDA COMPLETED SUCCESSFULLY")
print("File saved as: EDA_Result.xlsx")

